### PR TITLE
Update to latest bgfx

### PR DESCRIPTION
**Pull request by okwasniewski**
Hey, 

I'm doing another sync for visionOS work, especially to bring in the fix: 

- https://github.com/BabylonJS/bgfx/commit/3f3d3b443348eda809fc2b30857e208e7dddec88
- https://github.com/BabylonJS/bgfx/commit/0b73e8c7e22a2876a8979a4dd9b77d0686058090

### CODE REVIEW

**Comment by ryantrem** [comment]
Were you able to test this in Babylon React Native as well?
Which platforms have you tested with these changes in both BN and BRN (e.g. Windows, iOS, Android)?

**Comment by okwasniewski** [comment]
Hey @ryantrem, 

I didn't check it in Babylon React Native (yet). I'm going to try integrating my visionOS PR to Babylon React Native next week so I'm going to check other platforms too. I've tested visionOS and iOS. Could you test Windows and Android? 

I don't have any Windows/Android devices (I can test Android on a simulator but Im not sure if it works). 

Im running into some build issues on Windows on my PR, so it will probably need some additional work

**Review by CedricGuillemet — APPROVED** [review]

**Comment by CedricGuillemet** [comment]
I usually do a PR to check validation tests with BabylonNative. So, it needs a bgfx.cmake update and a BN PR.
If BN Validation tests are fine then BRN should be no problem.

**Comment by ryantrem** [comment]
Just checking, you haven't created a BN PR with this change to run it through validation tests yet, correct?

**Comment by okwasniewski** [comment]
@ryantrem 

> @okwasniewski Just checking, you haven't created a BN PR with this change to run it through validation tests yet, correct?

I'm sorry I've been busy with other stuff, I will create syncing PR tomorrow

**Comment by ryantrem** [comment]
No worries, I just remembered this and wanted to make sure you weren't waiting on us!

**Comment by ryantrem** [comment]
The BN draft PR to test this is here, correct?
https://github.com/BabylonJS/BabylonNative/pull/1408

**Pull request merged**
