### PR TITLE
fix: shader-spirv build issues on Windows

### PR DESCRIPTION
**Pull request by okwasniewski**
This PRs brings back this change after syncing with latest bgfx. I probably missed it in the merge resolution.

### CODE REVIEW

**Comment by bghgary** [comment]
I would not expect a merge conflict in this file. Are you saying you had to manually merge something here?

**Comment by okwasniewski** [comment]
> I would not expect a merge conflict in this file. Are you saying you had to manually merge something here?

Not sure, probably this got deleted in upstream repo, I didn't see any merge conflicts here but also couldn't find any reason this suddenly stopped working. I can go through commit history tomorrow and check it

**Comment by bghgary** [comment]
If this got deleted in the upstream, we need to fix the upstream. I'm fine if we want to do this here first, but the final solution needs to be upstream.

**Comment by okwasniewski** [comment]
@bghgary This is the change upstream: https://github.com/bkaradzic/bgfx/commit/8432a0a76d1755dd1c18fe743f46f034c3694728

**Comment by bghgary** [comment]
I'm guessing it's because of this: https://devblogs.microsoft.com/cppblog/announcing-full-support-for-a-c-c-conformant-preprocessor-in-msvc/

We probably need to enable this flag in the build.

**Comment by okwasniewski** [comment]
@bghgary I've added this flag in this PR https://github.com/BabylonJS/bgfx.cmake/pull/75

**Pull request closed without merging**
