### PR TITLE
Fix Apple build on old versions of Xcode

### PR DESCRIPTION
**Pull request by docEdub**

### CODE REVIEW

**Comment by docEdub** [comment]
I merged the upstream repo to bring in the D3D12 clear rect fix, which brought along changes that break the build on XCode versions 13 and lower due to the use of enum values like `MTLGPUFamilyApple8` from the SDK headers that are only available in XCode 14 and higher. Hard-coded numbers matching the SDK enum values were being used before. They were changed upstream in commit https://github.com/BabylonJS/bgfx/commit/c43c4479de1ba4290b8e9d4c4df1ed4b760e84dc.

**Comment by bghgary** [comment]
Are these the changes that have not been pushed upstream yet?

**Comment by docEdub** [comment]
Ya, I opened a PR upstream but it's not clear to me what changes it needs to get merged.

**Review by bghgary — APPROVED** [review]
We can take an updated version once the real version goes into bgfx.

**Pull request merged**
