### PR TITLE
(🍒 cherry pick) Add visionOS support

### PR DESCRIPTION
**Pull request by okwasniewski**
Hey,

This PR cherry picks PRs needed to make bgfx work on visionOS.

This is needed to bring BabylonNative to visionOS, here: https://github.com/BabylonJS/BabylonNative/pull/1384

### CODE REVIEW

**Comment by okwasniewski** [comment]
Another option would be to merge the latest changes from bgfx.

**Comment by okwasniewski** [comment]
cc: @bghgary (I saw you syncing the repo recently)

**Comment by bghgary** [comment]
We normally take the latest.

**Comment by okwasniewski** [comment]
Sure, that makes sense, I will create the merge PR if you don't mind.

**Pull request closed without merging**
